Configuration:
  status: warn
  monitorInterval: 30
  Properties:
    Property:
    - name: log.level.console
      value: info
    - name: log.path
      value: log
    - name: project.name
      value: szse
    - name: log.pattern
      value: '%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-30.30C{1.} : %m%n'
  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: ${log.pattern}
    RollingFile:
    - name: ROLLING_FILE
      fileName: ${log.path}/${project.name}.log
      filePattern: ${log.path}/historyRunLog/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.gz
      PatternLayout:
        pattern: ${log.pattern}
      Filters:
        ThresholdFilter:
        - level: error
          onMatch: ACCEPT
          onMismatch: NEUTRAL
        - level: warn
          onMatch: ACCEPT
          onMismatch: NEUTRAL
        - level: info
          onMatch: ACCEPT
          onMismatch: DENY
      Policies:
        TimeBasedTriggeringPolicy:
          modulate: true
          interval: 1
      DefaultRolloverStrategy:
        max: 100
  Loggers:
    Root:
      level: info
      AppenderRef:
      - ref: CONSOLE
      - ref: ROLLING_FILE
    Logger:
    - name: normal
      level: info
      additivity: false
      AppenderRef:
      - ref: ROLLING_FILE